services:
  db:
    image: "pgautoupgrade/pgautoupgrade:latest"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    init: true
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
